import { Oswald } from 'next/font/google'
import "./globals.css";
import Header from './components/Header'

// pick the weights you need
const oswald = Oswald({
  subsets: ['latin'],
  weight: ['300','400','500','600','700'],
  variable: '--font-oswald',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.variable}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
